export interface IItemCardData {
  id: number;
  type: string;
  title: string;
  cnt: number;
  list: IItem[];
}

export interface IItem {
  id: string;
  name_kor: string;
  name_eng: string;
  model_no: string;
  image_path: string;
  deep_link: string;
  bg_color: string;
  top_category_id: string;
  top_category_name: string;
  brand_name_eng: string;
  brand_name_kor: string;
  price: string;
  price_type: string;
  is_custody: number;
  is_bid_sell: number;
  is_bid_buy: number;
  is_deal: number;
  change_price_ratio: number;
  series_id: number;
  release_date: string;
  brand_id: number;
  is_display: number;
  display_price_kor: string;
  display_price_eng: string;
  series_name_kor: string;
  standard_release_date: string;
  min_price: number;
  bid_price: number;
  point: string;
  is_secondary: number;
  is_change_price_ratio: number;
  is_release_price_ratio: number;
  is_preowned: number;
  is_search_preowned: number;
  product_size_option_id: number;
  is_coupon: number;
}

export const ITEM_DUMMY: IItemCardData = {
  id: 1,
  type: "goods",
  title: "상품",
  cnt: 164807,
  list: [
    {
      id: "3",
      name_kor: "아디다스 휴먼 레이스 NMD 퍼렐 홀리 페스티벌 (코어 블랙)",
      name_eng: "adidas Human Race NMD Pharrell Holi Festival (Core Black)",
      model_no: "AC7033",
      image_path:
        "https://test-img.soldout.co.kr/items/2020/05/20/item-3-main.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F3%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "ADIDAS",
      brand_name_kor: "아디다스",
      price: "2,100,000,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 0,
      series_id: 22,
      release_date: "18/09/01",
      brand_id: 2,
      is_display: 1,
      display_price_kor: "",
      display_price_eng: "$250",
      series_name_kor: "NMD",
      standard_release_date: "2023-09-09 00:00:00",
      min_price: 2100000000,
      bid_price: 55000,
      point: "",
      is_secondary: 1,
      is_change_price_ratio: 0,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 68,
      is_coupon: 0,
    },
    {
      id: "17587",
      name_kor: "나이키 코비 A.D. 화이트 크롬",
      name_eng: "Nike Kobe A.D. White Chrome",
      model_no: "852425-110",
      image_path:
        "https://test-img.soldout.co.kr/items/2021/12/27/45e8f926-0d1e-4ed8-8311-f3b50fff4067.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F17587%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F0F3F7",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "NIKE",
      brand_name_kor: "나이키",
      price: "100,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 0,
      series_id: 6,
      release_date: "17/01/07",
      brand_id: 1,
      is_display: 1,
      display_price_kor: "",
      display_price_eng: "$170",
      series_name_kor: "코비",
      standard_release_date: "2017-01-07 00:00:00",
      min_price: 100000,
      bid_price: 222000,
      point: "",
      is_secondary: 1,
      is_change_price_ratio: 0,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 120826,
      is_coupon: 1,
    },
    {
      id: "45792",
      name_kor: "뉴발란스 990v4 MIU 키스 유나이티드 애로우 & 선 그레이 핑크",
      name_eng:
        "New Balance 990v4 Made in USA Kith United Arrows & Sons Grey Pink",
      model_no: "M990KT4",
      image_path:
        "https://test-img.soldout.co.kr/items/2022/08/16/b8096ea9-73a0-4dd2-a79e-50f468cb12df.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F45792%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "NEW BALANCE",
      brand_name_kor: "뉴발란스",
      price: "10,000원",
      price_type: "즉시구매가",
      is_custody: 0,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: -10,
      series_id: 0,
      release_date: "22/06/15",
      brand_id: 7,
      is_display: 1,
      display_price_kor: "",
      display_price_eng: "$235",
      series_name_kor: "",
      standard_release_date: "2022-06-15 00:00:00",
      min_price: 10000,
      bid_price: 0,
      point: "",
      is_secondary: 1,
      is_change_price_ratio: 0,
      is_release_price_ratio: 1,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 297333,
      is_coupon: 0,
    },
    {
      id: "1814",
      name_kor: "나이키 에어 폼포짓 원 파이터 젯",
      name_eng: "Nike Air Foamposite One Fighter Jet",
      model_no: "575420-001/CBBU3PS080BK/575420-001/CBBU3PS080BK/57542",
      image_path:
        "https://test-img.soldout.co.kr/items/2020/05/20/item-1814-main.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F1814%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F0F3F7",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "NIKE",
      brand_name_kor: "나이키",
      price: "50,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 150,
      series_id: 7,
      release_date: "13/02/09",
      brand_id: 1,
      is_display: 1,
      display_price_kor: "",
      display_price_eng: "$235",
      series_name_kor: "폼포짓",
      standard_release_date: "2023-08-28 00:00:00",
      min_price: 0,
      bid_price: 70000,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 1,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 0,
      is_coupon: 0,
    },
    {
      id: "1429258",
      name_kor: "아디다스 오리지널스 아디매틱 원더 클레이",
      name_eng: "Adidas Originals Adimatic Wonder Clay",
      model_no: "IE9862",
      image_path:
        "https://test-img.soldout.co.kr/external_image/2023/07/03/6ee23e03-c205-4add-9301-add58a96fad8.jpg/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F1429258%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "ADIDAS",
      brand_name_kor: "아디다스",
      price: "150,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 0,
      series_id: 0,
      release_date: "23/07/03",
      brand_id: 2,
      is_display: 1,
      display_price_kor: "139,000원",
      display_price_eng: "",
      series_name_kor: "",
      standard_release_date: "2023-07-03 00:00:00",
      min_price: 150000,
      bid_price: 100000,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 0,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 799695,
      is_coupon: 0,
    },
    {
      id: "1521644",
      name_kor: "일반 제품 등록 확인 - 수정 확인",
      name_eng: "dlfqks dlfqks tnwjd tnwjd",
      model_no: "dlfqks-test",
      image_path:
        "https://test-img.soldout.co.kr/defaults/default_item.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F1521644%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "2",
      top_category_name: "의류",
      brand_name_eng: "ABRICO",
      brand_name_kor: "abrico",
      price: "200,000원",
      price_type: "발매가",
      is_custody: 0,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 0,
      series_id: 0,
      release_date: "18/12/13",
      brand_id: 1132,
      is_display: 1,
      display_price_kor: "200,000원",
      display_price_eng: "",
      series_name_kor: "",
      standard_release_date: "2023-10-01 00:40:00",
      min_price: 0,
      bid_price: 0,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 0,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 0,
      product_size_option_id: 0,
      is_coupon: 0,
    },
    {
      id: "3188",
      name_kor: "나이키 에어 트레이너 1 미드 슈퍼 볼 홀로그램",
      name_eng: "Nike Air Trainer 1 Mid Super Bowl Hologram",
      model_no: "607081-900",
      image_path:
        "https://test-img.soldout.co.kr/items/2020/08/13/d8bca43e-ff24-45d0-9df7-fde08915c593.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F3188%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F0F3F7",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "NIKE",
      brand_name_kor: "나이키",
      price: "10,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: -80,
      series_id: 10,
      release_date: "23/10/01",
      brand_id: 1,
      is_display: 1,
      display_price_kor: "",
      display_price_eng: "$140",
      series_name_kor: "Other",
      standard_release_date: "2023-10-01 00:00:00",
      min_price: 10000,
      bid_price: 10000,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 0,
      is_release_price_ratio: 0,
      is_preowned: 1,
      is_search_preowned: 1,
      product_size_option_id: 68,
      is_coupon: 0,
    },
    {
      id: "2941",
      name_kor: "에어 조던 1 레트로 하이 OG 다크 모카",
      name_eng: "Jordan 1 Retro High OG Dark Mocha",
      model_no: "555088-105",
      image_path:
        "https://test-img.soldout.co.kr/items/2022/10/17/612167e2-94cf-41d6-bfe8-bb367f25645d.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F2941%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F8F4F4",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "JORDAN",
      brand_name_kor: "조던",
      price: "20,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 175,
      series_id: 23,
      release_date: "20/12/26",
      brand_id: 3,
      is_display: 1,
      display_price_kor: "199,000원",
      display_price_eng: "$170",
      series_name_kor: "1",
      standard_release_date: "2021-07-05 17:10:00",
      min_price: 20000,
      bid_price: 0,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 1,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 68,
      is_coupon: 0,
    },
    {
      id: "26129",
      name_kor: "뉴발란스 1500 MIUK 네이비 그레이 해리스 트위드",
      name_eng: "New Balance 1500 Made in UK Navy Grey Harris Tweed",
      model_no: "M1500HT",
      image_path:
        "https://test-img.soldout.co.kr/items/2022/04/28/07590578-93b2-41f7-8738-e77dbc416a1e.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F26129%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "NEW BALANCE",
      brand_name_kor: "뉴발란스",
      price: "20,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 13,
      series_id: 0,
      release_date: "21/12/10",
      brand_id: 7,
      is_display: 1,
      display_price_kor: "210원",
      display_price_eng: "",
      series_name_kor: "",
      standard_release_date: "2023-11-01 00:00:00",
      min_price: 20000,
      bid_price: 31000,
      point: "",
      is_secondary: 1,
      is_change_price_ratio: 1,
      is_release_price_ratio: 1,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 168426,
      is_coupon: 0,
    },
    {
      id: "6520",
      name_kor: "나이키 덩크 로우 레트로 화이트 블랙",
      name_eng: "Nike Dunk Low Retro White Black",
      model_no: "DD1391-100",
      image_path:
        "https://test-img.soldout.co.kr/items/2022/10/17/34f671c0-515b-4bab-9537-976a95f82e89.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F6520%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F0F3F7",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "NIKE",
      brand_name_kor: "나이키",
      price: "90,500원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 0,
      series_id: 3,
      release_date: "21/04/02",
      brand_id: 1,
      is_display: 1,
      display_price_kor: "129,000원",
      display_price_eng: "",
      series_name_kor: "덩크",
      standard_release_date: "2022-10-12 08:00:00",
      min_price: 90500,
      bid_price: 500000,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 0,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 900,
      is_coupon: 0,
    },
    {
      id: "1019",
      name_kor: "에어 조던 3 레트로 '88 슬램 시멘트 (2013) (GS)",
      name_eng: "Jordan 3 Retro White Cement '88 Dunk Contest 2013 (GS)",
      model_no: "398614-160",
      image_path:
        "https://test-img.soldout.co.kr/items/2020/05/20/item-1019-main.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F1019%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F8F4F4",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "JORDAN",
      brand_name_kor: "조던",
      price: "100,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: -80,
      series_id: 25,
      release_date: "13/02/06",
      brand_id: 3,
      is_display: 1,
      display_price_kor: "",
      display_price_eng: "$160",
      series_name_kor: "3",
      standard_release_date: "2013-02-06 00:00:00",
      min_price: 100000,
      bid_price: 0,
      point: "",
      is_secondary: 1,
      is_change_price_ratio: 0,
      is_release_price_ratio: 1,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 14477,
      is_coupon: 0,
    },
    {
      id: "1510070",
      name_kor: "빅로고 보아 플리스 점퍼 - 베이비핑크",
      name_eng: "빅로고 보아 플리스 점퍼 - 베이비핑크",
      model_no: "FBDJFL7357BP",
      image_path:
        "https://test-img.soldout.co.kr/external_image/2023/09/19/9ecbd9be-074b-4885-b5e0-2ff755cdc5f2.jpg/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F1510070%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "2",
      top_category_name: "의류",
      brand_name_eng: "FCMM",
      brand_name_kor: "fcmm",
      price: "500,000원",
      price_type: "즉시구매가",
      is_custody: 0,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 0,
      series_id: 0,
      release_date: "23/10/20",
      brand_id: 834,
      is_display: 1,
      display_price_kor: "89,000원",
      display_price_eng: "",
      series_name_kor: "",
      standard_release_date: "2023-10-20 09:00:00",
      min_price: 500000,
      bid_price: 0,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 0,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 0,
      product_size_option_id: 1089833,
      is_coupon: 0,
    },
    {
      id: "33893",
      name_kor: "아식스 타이거 젤 PTG MT 화이트 클래식 레드",
      name_eng: "Asics Tiger Gel-PTG MT White Classic Red",
      model_no: "1193A182-101",
      image_path:
        "https://test-img.soldout.co.kr/items/2022/06/16/bdff0cb1-0034-47e9-9e38-b1edc9ffb342.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F33893%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "ASICS",
      brand_name_kor: "아식스",
      price: "10,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 0,
      series_id: 0,
      release_date: "23/10/01",
      brand_id: 10,
      is_display: 1,
      display_price_kor: "",
      display_price_eng: "$200",
      series_name_kor: "",
      standard_release_date: "2023-10-01 00:30:00",
      min_price: 10000,
      bid_price: 50000,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 0,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 219632,
      is_coupon: 0,
    },
    {
      id: "37644",
      name_kor: "푸시 확인용 - 구매금지",
      name_eng:
        "슈프림 아크 워터 쇼츠 로열 (22SS) Supreme Arc Water Short Royal (22SS)",
      model_no: "",
      image_path:
        "https://test-img.soldout.co.kr/items/2022/07/01/54dfe60b-b8d4-43dd-9bb8-dc54b0544516.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F37644%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "2",
      top_category_name: "의류",
      brand_name_eng: "SUPREME",
      brand_name_kor: "슈프림",
      price: "12,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 150,
      series_id: 0,
      release_date: "22/06/30",
      brand_id: 33,
      is_display: 1,
      display_price_kor: "",
      display_price_eng: "$110",
      series_name_kor: "",
      standard_release_date: "2022-06-30 00:00:00",
      min_price: 12000,
      bid_price: 10000,
      point: "",
      is_secondary: 1,
      is_change_price_ratio: 1,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 0,
      product_size_option_id: 246089,
      is_coupon: 0,
    },
    {
      id: "3729",
      name_kor: "나이키 ISPA 로드 워리어 클리어 제이드",
      name_eng: "Nike ISPA Road Warrior Clear Jade",
      model_no: "CW9410-400",
      image_path:
        "https://test-img.soldout.co.kr/items/2020/10/20/3cd4f818-c534-4dfe-8ad5-8d79d8a25f8c.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F3729%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F0F3F7",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "NIKE",
      brand_name_kor: "나이키",
      price: "85,000원",
      price_type: "즉시구매가",
      is_custody: 0,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 0,
      series_id: 10,
      release_date: "20/10/23",
      brand_id: 1,
      is_display: 1,
      display_price_kor: "559,000원",
      display_price_eng: "",
      series_name_kor: "Other",
      standard_release_date: "2023-08-28 00:00:00",
      min_price: 85000,
      bid_price: 0,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 0,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 68,
      is_coupon: 0,
    },
    {
      id: "46274",
      name_kor:
        "메종 미하라 야스히로 웨인 VL OG 솔 레더 로우탑 스니커즈 화이트 레드",
      name_eng:
        "Maison Mihara Yasuhiro Wayne VL OG Sole Leather Low-top Sneakers White Red",
      model_no: "A09FW730-RED",
      image_path:
        "https://test-img.soldout.co.kr/items/2022/08/18/6b56d250-ce9d-4b0f-90e8-a6fe82c7d035.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F46274%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#FFFFFF",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "MAISON MIHARA YASUHIRO",
      brand_name_kor: "미하라 야스히로",
      price: "20,000원",
      price_type: "즉시구매가",
      is_custody: 0,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: -80,
      series_id: 0,
      release_date: "22/08/20",
      brand_id: 100,
      is_display: 1,
      display_price_kor: "",
      display_price_eng: "",
      series_name_kor: "",
      standard_release_date: "2022-08-20 00:00:00",
      min_price: 20000,
      bid_price: 0,
      point: "",
      is_secondary: 1,
      is_change_price_ratio: 1,
      is_release_price_ratio: 0,
      is_preowned: 1,
      is_search_preowned: 1,
      product_size_option_id: 300933,
      is_coupon: 0,
    },
    {
      id: "10170",
      name_kor: "뉴발란스 비전 레이서 제이든 스미스 피오니",
      name_eng: "New Balance Vision Racer Jaden Smith Peony",
      model_no: "MSVRCJSC",
      image_path:
        "https://test-img.soldout.co.kr/items/2021/05/14/352620e7-1192-45e7-9cf9-109806f798c2.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F10170%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "NEW BALANCE",
      brand_name_kor: "뉴발란스",
      price: "21,000,000원",
      price_type: "",
      is_custody: 1,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 150,
      series_id: 0,
      release_date: "21/05/17",
      brand_id: 7,
      is_display: 1,
      display_price_kor: "169,000원",
      display_price_eng: "",
      series_name_kor: "",
      standard_release_date: "2021-05-17 11:00:00",
      min_price: 21000000,
      bid_price: 30000,
      point: "",
      is_secondary: 1,
      is_change_price_ratio: 1,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 60753,
      is_coupon: 0,
    },
    {
      id: "11",
      name_kor: "아디다스 NMD HU 퍼렐 휴먼 비잉 샤프 블루",
      name_eng: "adidas NMD HU Pharrell Human Being Sharp Blue",
      model_no: "BB0618",
      image_path:
        "https://test-img.soldout.co.kr/items/2020/05/20/item-11-main.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F11%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "1",
      top_category_name: "스니커즈",
      brand_name_eng: "ADIDAS",
      brand_name_kor: "아디다스",
      price: "50,000원",
      price_type: "즉시구매가",
      is_custody: 0,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 66,
      series_id: 22,
      release_date: "16/09/29",
      brand_id: 2,
      is_display: 1,
      display_price_kor: "",
      display_price_eng: "$240",
      series_name_kor: "NMD",
      standard_release_date: "2016-09-29 00:00:00",
      min_price: 50000,
      bid_price: 40000,
      point: "",
      is_secondary: 1,
      is_change_price_ratio: 1,
      is_release_price_ratio: 1,
      is_preowned: 0,
      is_search_preowned: 1,
      product_size_option_id: 68,
      is_coupon: 0,
    },
    {
      id: "1521601",
      name_kor: "그레이 레더 LB 크로스바디 백 (XS) B236AIB022GRF",
      name_eng: "그레이 레더 LB 크로스바디 백 (XS) B236AIB022GRF",
      model_no: "B236AIB022GRF",
      image_path:
        "https://test-img.soldout.co.kr/external_image/2023/10/11/c16673ac-0fda-4d87-b83e-69e67b85e60e.jpg/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F1521601%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "40",
      top_category_name: "패션잡화",
      brand_name_eng: "BIMBAYLOLA",
      brand_name_kor: "bimbaylola",
      price: "60,000원",
      price_type: "즉시구매가",
      is_custody: 0,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 0,
      series_id: 0,
      release_date: "//",
      brand_id: 1182,
      is_display: 1,
      display_price_kor: "363,000원",
      display_price_eng: "",
      series_name_kor: "",
      standard_release_date: "-- ::",
      min_price: 60000,
      bid_price: 0,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 0,
      is_release_price_ratio: 0,
      is_preowned: 0,
      is_search_preowned: 0,
      product_size_option_id: 1125768,
      is_coupon: 0,
    },
    {
      id: "1492856",
      name_kor: "0829 라이프111",
      name_eng: "11",
      model_no: "",
      image_path:
        "https://test-img.soldout.co.kr/defaults/default_item.png/soldout/resize/564x564/optimize",
      deep_link:
        "msoldoutapp://webview/type=1&style=2&header=0&url=https%3A%2F%2Ftest.soldout.co.kr%2Ftrade%2Fproduct%2F1492856%3Fproduct_size_option_id%3D0%26open_size%3D0",
      bg_color: "#F5F5F5",
      top_category_id: "5",
      top_category_name: "라이프",
      brand_name_eng: "AACA",
      brand_name_kor: "aaca",
      price: "10,000원",
      price_type: "즉시구매가",
      is_custody: 0,
      is_bid_sell: 0,
      is_bid_buy: 0,
      is_deal: 1,
      change_price_ratio: 900,
      series_id: 0,
      release_date: "23/08/29",
      brand_id: 1001,
      is_display: 1,
      display_price_kor: "10,000원",
      display_price_eng: "",
      series_name_kor: "",
      standard_release_date: "2023-08-29 00:00:00",
      min_price: 10000,
      bid_price: 0,
      point: "",
      is_secondary: 0,
      is_change_price_ratio: 1,
      is_release_price_ratio: 1,
      is_preowned: 0,
      is_search_preowned: 0,
      product_size_option_id: 1026998,
      is_coupon: 0,
    },
  ],
};
